apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "spring-cloud-config-server.fullname" . }}
  labels:
{{ include "spring-cloud-config-server.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "spring-cloud-config-server.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "spring-cloud-config-server.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        {{- with .Values.podTemplate.annotations }}  
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8888
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: http
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: http
          {{- if not .Values.secrets.ignoreLocalSshSettings }}
          volumeMounts:
          - name: {{ include "spring-cloud-config-server.name" . }}-ssh-key
            readOnly: true
            mountPath: "/root/.ssh"
          {{- end}}
          env:
          {{- if .Values.config.gitUri }}
          - name: SPRING_CLOUD_CONFIG_SERVER_GIT_URI
            value: "{{ .Values.config.gitUri }}"
          {{- else }}
          - name: SPRING_PROFILES_ACTIVE
            value: "native"
          {{- end}}
          {{- if .Values.config.gitSearchpath }}
          - name: SPRING_CLOUD_CONFIG_SERVER_GIT_SEARCHPATHS
            value: "{{ .Values.config.gitSearchpath }}"
          {{- end}}
          - name: SPRING_CLOUD_CONFIG_SERVER_GIT_IGNORELOCALSSHSETTINGS
            value: "{{ .Values.secrets.ignoreLocalSshSettings }}"
          - name: SPRING_CLOUD_CONFIG_SERVER_GIT_STRICTHOSTKEYCHECKING
            value: "{{ .Values.secrets.strictHostKeyChecking }}"
          {{- if .Values.secrets.required }}
          - name: SPRING_CLOUD_CONFIG_SERVER_GIT_USERNAME
            valueFrom:
              secretKeyRef:
                name: "{{ include "spring-cloud-config-server.fullname" . }}"
                key: "gitUsername"
          - name: SPRING_CLOUD_CONFIG_SERVER_GIT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: "{{ include "spring-cloud-config-server.fullname" . }}"
                key: "gitPassword"
          {{- end}}      
          {{- if .Values.extraEnv }}
            {{- toYaml .Values.extraEnv | nindent 10 }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- if not .Values.secrets.ignoreLocalSshSettings }}
      volumes:
      - name: {{ include "spring-cloud-config-server.name" . }}-ssh-key
        secret: 
          secretName: {{ include "spring-cloud-config-server.name" . }}-ssh-key
      {{- end}}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
